### ISSUE TITLE
Examples fail to build

### ISSUE THREAD

**Issue by subdavis** [OpenGeoscience/geojs#1163]
```
brandon@GrayCris:~/github.com/geojs (master)
~$ yarn examples
yarn run v1.22.15
$ node examples/build.js && webpack --config webpack-examples.config.js && node tutorials/build.js && webpack --config webpack-tutorials.config.js && node ./tests/runners/server.js --host "${HOST-}" --port ${PORT-8082} --dist
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
/home/brandon/github.com/geojs/node_modules/docco/docco.js:129
      _results.push(section.docsHtml = marked(section.docsText));
                                       ^

TypeError: marked is not a function
    at format (/home/brandon/github.com/geojs/node_modules/docco/docco.js:129:40)
    at /home/brandon/github.com/geojs/node_modules/docco/docco.js:47:11
    at /home/brandon/github.com/geojs/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

System info

```
brandon@GrayCris:~/github.com/geojs (master)
~$ yarn --version
1.22.15
brandon@GrayCris:~/github.com/geojs (master)
~$ node --version
v16.13.0
```

Also tried with Node v12.

**Comment by subdavis** [comment]
Yarn is unsupported on this project, switched to NPM and it works.

**Comment by manthey** [comment]
Do you know what we'd need to change to support yarn?

**Comment by subdavis** [comment]
I don't think it makes sense to support both -- you'd have 2 lock files to contend with.

A direct link to https://geojs.readthedocs.io/en/latest/developers.html from the README would have helped though.  I looked briefly for developer docs and didn't find any, so I just opened up `package.json`
